In [19]:
import pandas as pd
from nba_api.stats.endpoints import leaguegamelog
from nba_api.stats.endpoints import boxscoretraditionalv2

In [2]:
seasons = list(range(2011,2021))

In [3]:
regular_games = leaguegamelog.LeagueGameLog(season = 2010, season_type_all_star = "Regular Season")
regular_games = regular_games.get_data_frames()[0]
for s in seasons:
    dat = leaguegamelog.LeagueGameLog(season = s, season_type_all_star = "Regular Season")
    dat = dat.get_data_frames()[0]
    regular_games = pd.concat([regular_games, dat])

In [4]:
regular_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22010,1610612745,HOU,Houston Rockets,0021000003,2010-10-26,HOU @ LAL,L,240,38,...,37,53,25,6,7,21,25,110,-2,0
1,22010,1610612747,LAL,Los Angeles Lakers,0021000003,2010-10-26,LAL vs. HOU,W,240,40,...,30,44,21,11,4,12,24,112,2,0
2,22010,1610612738,BOS,Boston Celtics,0021000001,2010-10-26,BOS vs. MIA,W,240,32,...,34,42,25,6,4,20,19,88,8,0
3,22010,1610612748,MIA,Miami Heat,0021000001,2010-10-26,MIA @ BOS,L,240,27,...,28,39,15,10,6,17,21,80,-8,0
4,22010,1610612756,PHX,Phoenix Suns,0021000002,2010-10-26,PHX @ POR,L,240,36,...,23,30,15,3,4,19,19,92,-14,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2155,22020,1610612749,MIL,Milwaukee Bucks,0022001068,2021-05-16,MIL @ CHI,L,240,38,...,31,41,14,13,5,12,16,112,-6,1
2156,22020,1610612747,LAL,Los Angeles Lakers,0022001072,2021-05-16,LAL @ NOP,W,240,45,...,34,42,30,14,5,10,16,110,12,1
2157,22020,1610612740,NOP,New Orleans Pelicans,0022001072,2021-05-16,NOP vs. LAL,L,240,37,...,39,47,26,4,5,21,18,98,-12,1
2158,22020,1610612758,SAC,Sacramento Kings,0022001077,2021-05-16,SAC vs. UTA,L,240,42,...,34,39,24,10,5,13,22,99,-22,1
2159,22020,1610612762,UTA,Utah Jazz,0022001077,2021-05-16,UTA @ SAC,W,240,41,...,41,50,28,9,3,16,14,121,22,1

In [5]:
playoff_games = leaguegamelog.LeagueGameLog(season = 2010, season_type_all_star = "Playoffs")
playoff_games = playoff_games.get_data_frames()[0]
for s in seasons:
    dat = leaguegamelog.LeagueGameLog(season = s, season_type_all_star = "Playoffs")
    dat = dat.get_data_frames()[0]
    playoff_games = pd.concat([playoff_games, dat])

In [6]:
playoff_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,42010,1610612741,CHI,Chicago Bulls,0041000101,2011-04-16,CHI vs. IND,W,240,36,...,28,49,18,6,9,15,21,104,5,0
1,42010,1610612754,IND,Indiana Pacers,0041000101,2011-04-16,IND @ CHI,L,240,39,...,21,34,21,8,6,12,25,99,-5,0
2,42010,1610612737,ATL,Atlanta Hawks,0041000131,2011-04-16,ATL @ ORL,W,240,38,...,24,29,19,8,1,10,28,103,10,0
3,42010,1610612753,ORL,Orlando Magic,0041000131,2011-04-16,ORL vs. ATL,L,240,34,...,27,40,15,3,3,18,24,93,-10,0
4,42010,1610612755,PHI,Philadelphia 76ers,0041000111,2011-04-16,PHI @ MIA,L,240,35,...,27,39,22,8,2,9,25,89,-8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,42020,1610612755,PHI,Philadelphia 76ers,0042000202,2021-06-08,PHI vs. ATL,W,240,46,...,31,37,29,10,8,9,18,118,16,1
96,42020,1610612746,LAC,LA Clippers,0042000221,2021-06-08,LAC @ UTA,L,240,36,...,33,42,22,3,6,9,24,109,-3,1
97,42020,1610612762,UTA,Utah Jazz,0042000221,2021-06-08,UTA vs. LAC,W,240,37,...,34,46,18,5,6,7,24,112,3,1
98,42020,1610612756,PHX,Phoenix Suns,0042000232,2021-06-09,PHX vs. DEN,W,240,45,...,44,52,27,3,4,7,18,123,25,1
99,42020,1610612743,DEN,Denver Nuggets,0042000232,2021-06-09,DEN @ PHX,L,240,36,...,35,46,24,4,6,11,21,98,-25,1

In [7]:
teams = dat.drop_duplicates(subset='TEAM_ID', keep="last")
teams = teams[["TEAM_ID", "TEAM_NAME"]]
teams = teams.reset_index(drop = True)
teams

       TEAM_ID               TEAM_NAME
0   1610612748              Miami Heat
1   1610612738          Boston Celtics
2   1610612764      Washington Wizards
3   1610612752         New York Knicks
4   1610612763       Memphis Grizzlies
5   1610612757  Portland Trail Blazers
6   1610612747      Los Angeles Lakers
7   1610612742        Dallas Mavericks
8   1610612751           Brooklyn Nets
9   1610612749         Milwaukee Bucks
10  1610612737           Atlanta Hawks
11  1610612755      Philadelphia 76ers
12  1610612746             LA Clippers
13  1610612762               Utah Jazz
14  1610612756            Phoenix Suns
15  1610612743          Denver Nuggets

In [8]:
reg_ids = regular_games["GAME_ID"].unique()

In [20]:
bs_trad_regular = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id = reg_ids[0])
bs_trad_regular = bs_trad_regular.get_data_frames()[0]
for i in range(1, len(reg_ids)):
    dat = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id = reg_ids[i])
    dat = dat.get_data_frames()[0]
    bs_trad_regular = pd.concat([bs_trad_regular, dat])

In [21]:
bs_trad_regular

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0021000003,1610612745,HOU,Houston,2203,Shane Battier,Shane,F,,31:24,...,2.0,4.0,6.0,4.0,0.0,2.0,2.0,3.0,3.0,9.0
1,0021000003,1610612745,HOU,Houston,2449,Luis Scola,Luis,F,,33:11,...,4.0,12.0,16.0,4.0,1.0,0.0,4.0,4.0,18.0,7.0
2,0021000003,1610612745,HOU,Houston,2397,Yao Ming,ao Ming,C,,23:21,...,4.0,7.0,11.0,2.0,0.0,2.0,4.0,6.0,9.0,-6.0
3,0021000003,1610612745,HOU,Houston,2755,Kevin Martin,Kevin,G,,29:29,...,1.0,2.0,3.0,2.0,0.0,1.0,4.0,4.0,26.0,4.0
4,0021000003,1610612745,HOU,Houston,201166,Aaron Brooks,Aaron,G,,41:39,...,1.0,2.0,3.0,9.0,0.0,0.0,2.0,0.0,24.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22,0022001077,1610612758,SAC,Sacramento,1629657,Kyle Guy,Kyle,,,18:38,...,0.0,6.0,6.0,5.0,2.0,0.0,1.0,2.0,6.0,-13.0
23,0022001077,1610612758,SAC,Sacramento,1630218,Robert Woodard II,Robert,,,11:09,...,1.0,2.0,3.0,1.0,0.0,1.0,0.0,1.0,2.0,1.0
24,0022001077,1610612758,SAC,Sacramento,203090,Maurice Harkless,Maurice,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,0022001077,1610612758,SAC,Sacramento,1629713,Justin James,Justin,,DNP - Injury/Illness,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,0022001077,1610612758,SAC,Sacramento,202355,Hassan Whiteside,Hassan,,DNP - Injury/Illness,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
playoff_ids = playoff_games["GAME_ID"].unique()

In [26]:
bs_trad_playoff = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id = playoff_ids[0])
bs_trad_playoff = bs_trad_playoff.get_data_frames()[0]
for i in range(1, len(playoff_ids)):
    dat = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id = playoff_ids[i])
    dat = dat.get_data_frames()[0]
    bs_trad_playoff = pd.concat([bs_trad_playoff, dat])

In [27]:
bs_trad_playoff

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0041000101,1610612754,IND,Indiana,101122,Danny Granger,Danny,F,,39:50,...,1.0,5.0,6.0,3.0,1.0,1.0,1.0,2.0,24.0,-5.0
1,0041000101,1610612754,IND,Indiana,201946,Tyler Hansbrough,Tyler,F,,35:21,...,2.0,2.0,4.0,2.0,1.0,0.0,2.0,4.0,22.0,-1.0
2,0041000101,1610612754,IND,Indiana,201579,Roy Hibbert,Roy,C,,32:19,...,5.0,3.0,8.0,1.0,1.0,1.0,2.0,5.0,11.0,-1.0
3,0041000101,1610612754,IND,Indiana,202331,Paul George,Paul,G,,23:19,...,0.0,2.0,2.0,1.0,0.0,2.0,1.0,2.0,2.0,-7.0
4,0041000101,1610612754,IND,Indiana,201954,Darren Collison,Darren,G,,34:00,...,1.0,5.0,6.0,9.0,2.0,1.0,1.0,2.0,17.0,-3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,0042000232,1610612756,PHX,Phoenix,1630188,Jalen Smith,Jalen,,,6:05,...,2.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,-6.0
26,0042000232,1610612756,PHX,Phoenix,204038,Langston Galloway,Langston,,,6:05,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,-6.0
27,0042000232,1610612756,PHX,Phoenix,202734,E'Twaun Moore,E'Twaun,,,6:05,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,7.0,-6.0
28,0042000232,1610612756,PHX,Phoenix,1628975,Jevon Carter,Jevon,,,6:05,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,-6.0
29,0042000232,1610612756,PHX,Phoenix,1630234,Ty-Shon Alexander,Ty-Shon,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
teams.to_csv("teams")